# Generated by Django 4.2.2 on 2023-07-02 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1000)),
                ("price", models.FloatField(default=0.0)),
                ("mining_speed", models.FloatField(default=0.0)),
                ("validity", models.IntegerField(default=7)),
            ],
            options={
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=1000)),
                ("option1", models.CharField(max_length=1000)),
                ("option2", models.CharField(max_length=1000)),
                ("option3", models.CharField(max_length=1000)),
                ("option4", models.CharField(max_length=1000)),
                ("answer", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="ScratchCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scratch", models.CharField(max_length=1000)),
                ("win_amount", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[("Free", "Free"), ("Premium", "Premium")],
                        default="Free",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Scratch Card",
            },
        ),
        migrations.CreateModel(
            name="Spin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("spin", models.CharField(max_length=1000)),
                ("win_amount", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[("Free", "Free"), ("Premium", "Premium")],
                        default="Free",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Spin",
            },
        ),
        migrations.CreateModel(
            name="VisitWebsites",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=1000)),
                ("condition", models.CharField(max_length=1000)),
                ("thumbnail", models.ImageField(upload_to="thumbnail/")),
                ("visit_ammount", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Visit Websites",
            },
        ),
        migrations.AddField(
            model_name="newuser",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="newuser",
            name="reffer_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="PackagePurchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(default=0.0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Package Purchase",
            },
        ),
        migrations.CreateModel(
            name="EarnedHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=1000)),
                ("amount", models.FloatField(default=0.0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Earned History",
            },
        ),
    ]
