# Generated by Django 4.2.2 on 2023-07-18 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0006_refferedmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="reffer_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
