# Generated by Django 4.2.2 on 2023-07-18 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0007_alter_newuser_reffer_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refferedmodel",
            name="reffered_user",
        ),
        migrations.RemoveField(
            model_name="refferedmodel",
            name="user",
        ),
        migrations.AddField(
            model_name="refferedmodel",
            name="reffered_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reffered_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refferedmodel",
            name="reffered_to",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reffered_to",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
