# Generated by Django 4.2.2 on 2023-07-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0008_remove_refferedmodel_reffered_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("path", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "Notification",
            },
        ),
        migrations.AddField(
            model_name="newuser",
            name="mining_speed",
            field=models.FloatField(default=0.0),
        ),
    ]
