# Generated by Django 4.2.2 on 2023-07-28 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0009_notification_newuser_mining_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrowRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(default=0.0)),
                ("phone", models.CharField(max_length=1000)),
                ("address", models.CharField(max_length=1000)),
                ("method", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Withdrow Request",
            },
        ),
    ]
