# Generated by Django 4.2.2 on 2023-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0015_packagepurchase_phone_packagepurchase_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packagemodel",
            old_name="id",
            new_name="package_id",
        ),
        migrations.RemoveField(
            model_name="packagemodel",
            name="validity",
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="transaction_type",
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newuser",
            name="mining_speed",
            field=models.FloatField(default=1.0),
        ),
    ]
