# Generated by Django 4.2.2 on 2023-08-01 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0016_rename_id_packagemodel_package_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packagemodel",
            old_name="package_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="packagepurchase",
            old_name="package",
            new_name="package_id",
        ),
        migrations.RemoveField(
            model_name="withdrowrequest",
            name="phone",
        ),
        migrations.AddField(
            model_name="newuser",
            name="canWithdraw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newuser",
            name="minimum_withdraw_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="newuser",
            name="withdraw_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WithdrowHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(default=0.0)),
                ("method", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Withdrow History",
            },
        ),
    ]
